baseURL = "https://til-syarif-25.pages.dev/"
languageCode = "id"
title = "Today I Learned"
theme = "PaperMod"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardLineBreak = true
      unsafe = true

[params]
  homeInfoParams = {Title = "Today I Learned", Content = "Hal-hal kecil yang saya pelajari setiap hari."}
  ShowReadingTime = true
  ShowTags = true

[taxonomies]
  tag = "tags"

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 10

[[menu.main]]
  name = "About Me"
  url = "/about/"
  weight = 20
